require("yuki.plugins-setup")
require("yuki.core.options")
require("yuki.core.keymaps")
require("yuki.core.colorscheme")
require("yuki.plugins.nvim-tree")
require("yuki.plugins.lualine")
require("yuki.plugins.telescope")
require("yuki.plugins.nvim-cmp")
require("yuki.plugins.lsp.mason")
require("yuki.plugins.lsp.lspconfig")
-- require("yuki.plugins.lsp.lspsaga")
require("yuki.plugins.treesitter")
require("yuki.plugins.gitsigns")
require("yuki.plugins.toggleterm")
